### ISSUE TITLE
nginx-verdaccio: is not working with other location path

### ISSUE THREAD

**Issue by admir86** [verdaccio/docker-examples#10]
the static files under -/static can not be found, if I change the location in verdaccio-conf
```
server {
  listen 80 default_server;
	access_log /var/log/nginx/verdaccio.log;
	charset utf-8;
  location /npm_dev/ {
    proxy_pass              http://verdaccio:4873/;
    proxy_set_header        Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_ssl_session_reuse off;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }
}
```

![image](https://user-images.githubusercontent.com/36576424/41766492-81d6433e-7607-11e8-98a4-d4ff6fcc6447.png)

does I need additional configuration for the proxy? or is the location (-/static) of the static files in verdaccio a problem, especially the hyphen in the path?

same problem with apache-verdaccio example

**Comment by juanpicado** [comment]
Hi @admir86 the issue will be fixed https://github.com/verdaccio/docker-examples/issues/10 and also I updated the nginx examples.

**Comment by juanpicado** [comment]
Thanks for reporting this.
