### ISSUE TITLE
How to test LDAP Connection

### ISSUE THREAD

**Issue by nsa5953** [verdaccio/docker-examples#17]
I am trying to setup Verdaccio on Docker container, where as I am able to launch Verdaccio with apache reverse proxy, but when I am trying to setup LDAP, where my container will interact with external active directory I am unable to do so, 

could you please help me on how to setup Verdaccio which will interact with my company's directory server? and how to test this connection?

**Comment by juanpicado** [comment]
Have you checked this example https://github.com/verdaccio/docker-examples/tree/master/ldap-verdaccio ?

**Comment by nsa5953** [comment]
Yes I have setup this ldap-verdaccio with docker-compose, whereas I see that you have crated your own openLDAP server and users are being authenticated against openLDAP server. 
but I want to connect  Verdaccio and authenticate users against my corporate active directory

**Comment by juanpicado** [comment]
I'm not LDAP user but. I'd asume is just matter of change configuration. Somehow, if you have a specific issue perhaps StackOverFlow or the plugin owner repo might provide you better help support.
