### ISSUE TITLE
update link in Readme for S3 storage example.

### ISSUE THREAD

**Issue by angelcos** [verdaccio/docker-examples#23]
Just that.

**Comment by juanpicado** [comment]
Could you do it ?

**Comment by superbiger** [comment]
@juanpicado

**Comment by Kaifuny** [comment]
@juanpicado 
https://github.com/verdaccio/docker-examples/pull/24

**Comment by angelcos** [comment]
> 
> 
> Could you do it ?

i tried, but I could't make it work.

**Comment by juanpicado** [comment]
Thanks @superbiger for https://github.com/verdaccio/docker-examples/pull/24

@angelcos what's the issue you are having?
