### ISSUE TITLE
Example with Docker compose with https

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/docker-examples#6]
I'd be great to have

- Example using https with docker-compose
- Example with Apache or Nginx

**Comment by ryanhanwu** [comment]
I've set up Docker+Nginx+SSL+Verdaccio successfully, this is my key configs - https://gist.github.com/ryanhanwu/321f477550424a1f76b1ccf360c36572#file-config-yaml-L50

**Comment by juanpicado** [comment]
It's a different approach that I was thinking off, but is also valid since you are using `url_prefix`. We have already a nginx example (https://github.com/verdaccio/docker-examples/tree/master/nginx-verdaccio) using only HTTP, however, it would be cool to have another one following your approach :-)  Willing to PR?

**Comment by ryanhanwu** [comment]
Sure! should I add a new folder named `nginx-verdaccio-ssl`?

**Comment by juanpicado** [comment]
Sure 👍  !!

**Comment by kopax** [comment]
Hi guys, do you know if the LDAP plugin is now functional for verdaccio ?

**Comment by juanpicado** [comment]
@kopax  https://www.npmjs.com/package/verdaccio-ldap this one?
