### ISSUE TITLE
Kubernetes Helm Chart

### ISSUE THREAD

**Issue by etiennetremel** [verdaccio/docker-examples#8]
I added Verdaccio to the Kubernetes package manager:
- Source: https://github.com/kubernetes/charts/tree/master/stable/verdaccio
- KubeApps: https://kubeapps.com/charts/stable/verdaccio

This allow quick deployment of Verdaccio to any Kubernetes cluster via [Helm](https://helm.sh/):

```
$ helm install stable/verdaccio
```

Maybe worth to mention it somewhere?

I was looking into adding the logo there, can I use that one: ![Verdaccio Logo](https://github.com/verdaccio/verdaccio.github.io/blob/master/css/icon/package.png)

**Comment by juanpicado** [comment]
Yeah ! I noticed that addition, thanks so much !! 

Logos are here: https://github.com/verdaccio/verdaccio/tree/master/assets

@rodriguesbreno could you provide us a set of `verdaccio` logos on image format (png, jpeg) for distribution?

**Comment by juanpicado** [comment]
@etiennetremel Could you PR such valuable information on https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md ? or Perhaps create a new file called `kubernetes.md` and linked it from `docker.md`?

**Comment by AvailCat** [comment]
@etiennetremel Logo image, source file: https://github.com/verdaccio/verdaccio/tree/master/assets

**Comment by juanpicado** [comment]
@Meeeeow but the format is SVG ... kinda hard to use. We need to provide something ready to use.

**Comment by brenordr** [comment]
I will provide. SVG is better for webpages. I'll submit a PR to the main repo with the exported files.

**Comment by etiennetremel** [comment]
PR for the logo: https://github.com/kubernetes/charts/pull/2943

**Comment by juanpicado** [comment]
@etiennetremel FYI https://github.com/verdaccio/verdaccio/tree/master/assets/bitmap there is a new set of logos. Thanks @rodriguesbreno

**Comment by juanpicado** [comment]
@etiennetremel we have a new set of logos , the same one we use in cloudron, Twitter, Docker Hub, etc. I think will look much better than the current one. Could you update it?

https://github.com/verdaccio/verdaccio/tree/master/assets/bitmap/logo

![screen shot 2017-12-20 at 7 28 31 am](https://user-images.githubusercontent.com/558752/34194111-6cdb6022-e557-11e7-833b-fdcb7cdb6d9b.png)
